### ISSUE TITLE
大佬，你这个支持外接显示器么？

### ISSUE THREAD

**Issue by yuan1129** [cyqxyy/Thinkpad-E450-OpenCore#1]

**Comment by cyqxyy** [comment]
HDMI驱动不起来

**Comment by yuan1129** [comment]
> HDMI驱动不起来

好的，谢谢大佬。非常感谢你提供EFI，用着很爽

**Comment by yuan1129** [comment]
> HDMI驱动不起来

大佬，现在支持HDMI了？

**Comment by cyqxyy** [comment]
@yuan1129 是的，我自己试是可以的

**Comment by yuan1129** [comment]
大佬，我用你这个EFI + Big Sur 11.6 + OpenCore 0.7.4，在重新安装的时候，安装界面会花屏
![WechatIMG155](https://user-images.githubusercontent.com/1085600/142430937-a2ee7995-4835-4721-a8e7-1df9c0b1b39e.jpeg)

**Comment by cyqxyy** [comment]
> 大佬，我用你这个EFI + Big Sur 11.6 + OpenCore 0.7.4，在重新安装的时候，安装界面会花屏 ![微信IMG155](https://user-images.githubusercontent.com/1085600/142430937-a2ee7995-4835-4721-a8e7-1df9c0b1b39e.jpeg)

 没遇到过，你可以试试用我之前的EFI，安装后再替换成新的试试。

**Comment by yuan1129** [comment]
我用OC0.7.1-BigSur11.5.1这个版本的，安装11.6后，替换成新的，也是出现这个问题。

**Comment by cyqxyy** [comment]
> 我用OC0.7.1-BigSur11.5.1这个版本的，安装11.6后，替换成新的，同样出现这个问题。

估计你得自己找找原因了，我是参考[黑苹果解决HDMI输出问题
](https://www.bilibili.com/video/av800790316/)这个视频弄的

**Comment by yuan1129** [comment]
谢谢大佬，我看你的图片上显示的是内置显示器分辨率是1366x768，我的分辨率是1920x1080，有可能这个不一样导致的
